# Generated by Django 4.1.3 on 2022-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='gallery/')),
            ],
        ),
    ]
