# Generated by Django 4.1.3 on 2022-12-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo_5',
        ),
    ]
