# Generated by Django 4.1.3 on 2022-12-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
    ]
