# Generated by Django 4.1.3 on 2022-12-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('dessert_id', models.AutoField(primary_key=True, serialize=False)),
                ('dessert_name', models.CharField(max_length=50)),
                ('dessert_description', models.CharField(max_length=500)),
                ('dessert_weight', models.IntegerField()),
                ('dessert_price', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
            options={
                'ordering': ['dessert_name'],
            },
        ),
    ]
