# Generated by Django 4.1.3 on 2022-12-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_dessert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_weight',
            field=models.FloatField(),
        ),
    ]
